# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - azure-pipelines

pool: Default

steps:
  - checkout: self  # self represents the repo where the initial Pipelines YAML file was found
    clean: false # don't clean up to use previously built dependencies
  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'
  - script: |
      export PATH=$PATH:/root/.cargo/bin
      cargo build -vv
    displayName: 'Build MM2'
  - script: |
      export PATH=$PATH:/root/.cargo/bin
      cargo test -- --nocapture
    displayName: 'Test MM2'
  # Use cURL to upload files.
  # https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/curl-upload-files?view=vsts
  - task: cURLUploader@2
    inputs:
      files: 'target/debug/mm2'
      authType: 'userAndPass' # Optional. Options: serviceEndpoint, userAndPass
      #serviceEndpoint: # Required when authType == ServiceEndpoint
      username: $(SFTP_UPLOAD_USER)
      password: $(SFTP_UPLOAD_PASSWORD)
      url: 'sftp://195.201.0.6' # Required when authType == UserAndPass
      remotePath: 'uploads' # Optional
      #options: # Optional
      #redirectStderr: true # Optional