# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - azure-pipelines


jobs:
  - template: azure-pipelines-job.yml  # Template reference
    parameters:
      name: 'MM2 Linux'
      os: 'Linux'

  - template: azure-pipelines-job.yml  # Template reference
    parameters:
      name: 'MM2 MacOS'
      os: 'Darwin'

  - template: azure-pipelines-job.yml  # Template reference
    parameters:
      name: 'MM2 Windows'
      os: 'Windows_NT'