# Enable unstable features on stable and beta channels (unstable features are available by default on nightly).
# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#unstable_features
unstable_features = true

# Maximum width of each line.
# Default: 100
# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#max_width
max_width = 120

# This option can be used to simplify the management and bulk updates of the granular width configuration settings
# (fn_call_width, attr_fn_like_width, struct_lit_width, struct_variant_width, array_width, chain_width, single_line_if_else_max_width),
# that respectively control when formatted constructs are multi-lined/vertical based on width.
# Note: depricated since 2.0, use width_heuristics:
# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#width_heuristics
use_small_heuristics = "Max"

# Break comments to fit on the line
# Note: Unstable
# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#wrap_comments
wrap_comments = true

# Put single-expression functions on a single line
# Note: Unstable
# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#fn_single_line
fn_single_line = true

# Indent style of imports
# Note: Unstable
# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#imports_indent
imports_indent = "Visual"

# Write an item and its attribute on the same line if their combined width is below a threshold
# Note: Unstable
# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#inline_attribute_width
inline_attribute_width = 65

# Put a trailing comma after a block based match arm (non-block arms are not affected)
# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#match_block_trailing_comma
match_block_trailing_comma = true

# Merge multiple imports into a single nested import.
# Note: Unstable
# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#merge_imports
merge_imports = true

# Unix or Windows line endings
# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#newline_style
newline_style = "Unix"

# When structs, slices, arrays, and block/array-like macros are used as the last argument in an expression list,
# allow them to overflow (like blocks/closures) instead of being indented on a new line.
# Note: Unstable
# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#overflow_delimited_expr
overflow_delimited_expr = true

# Number of spaces per tab
# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#tab_spaces
tab_spaces = 4

# Use field initialize shorthand if possible.
# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#use_field_init_shorthand
use_field_init_shorthand = true
